### ISSUE TITLE
Crash when in third person

### ISSUE THREAD

**Issue by GrandmaPork** [CartoonishVillain/Incapacitated#16]
When using the most recent version of your mod in my modpack. Not entirely sure what causes it but it's happened multiple times now and *potentially* can lock you out of your world. havent done a deep dive on it
![image](https://github.com/CartoonishVillain/Incapacitated/assets/109642282/20ecf3b1-a36c-4af9-9194-73f852814110)
[crash-2024-05-22_20.21.11-client.txt](https://github.com/CartoonishVillain/Incapacitated/files/15410025/crash-2024-05-22_20.21.11-client.txt)
can provide more information if needed

**Comment by GrandmaPork** [comment]
okay leawind's third person mod causes it (this is it without the mod)
![2024-05-22_20 32 47](https://github.com/CartoonishVillain/Incapacitated/assets/109642282/34a13f38-fae4-49be-ae2c-158ec0ed4d34)

**Comment by CartoonishVillain** [comment]
The crash log reports the third person mod as the source of the crash. But it's strange that the conflict exists with incapacitated. A quick glance at the code that's reported doesn't reveal to me what happened here. 


Maybe the third person mod _really_ doesn't like me forcing poses the way I do, but that's a guess more than anything, and if that is the case.. well.. that's part of the whole. Being incapacitated ordeal. 

I don't really know what I can do to aid this situation. I may tinker with this for a bit but unless something more shows up between my tinkering or otherwise about how this can get fixed, I may close this and point you to their issue tracker instead.

**Comment by GrandmaPork** [comment]
i'll bring it up with them as well. it seems to only happen when a player is forced into prone through this mod and not any others, like parcool which lets you go into prone by hitting 'c'

**Comment by CartoonishVillain** [comment]
Thanks for that additional information! When I have the free time I'll look into how exactly parcool handles their forced pose states and see how it differs from my implementation

**Comment by GrandmaPork** [comment]
yeah no problem

**Comment by Leawind** [comment]
It's my problem. It should be already fixed in later versions of LTP

**Comment by GrandmaPork** [comment]
Appreciated

**Comment by CartoonishVillain** [comment]
Oh! Thank you! In such a case, I'll close this issue.
