### ISSUE TITLE
Use with corpse complex mod clears inventory after revive

### ISSUE THREAD

**Issue by Kzeroko** [CartoonishVillain/Incapacitated#2]
A compatibility issue with TheIllusiveC4's corpse complex mod.
Version:1.16.5
1. Set corpsecomplex config to No item drop on death.
2. Get killed and revive.
3. All items are gone.

**Comment by CartoonishVillain** [comment]
I'll attempt to investigate, but it right now just sounds like they don't account for the death event getting canceled, which is entirely how this mod operates.

From a preliminary inspection it would appear the following is what happens:

- You take enough damage to die, and their side kicks in to handle the inventory
- My mod kicks in and prevents you from actually dying
- Because you didn't respawn as they were expecting, their scheme for handling inventory goes incomplete.

With their mod running these at the highest priority, there isn't much I can do besides upping my priority one tier, and trying to get them to lower their priority to the lowest tier, checking for the event to be canceled before handling player inventories. 

Note: This analysis is from a very quick glance at potentially related code. I am still very unfamiliar with how the mod attempts to operate as a whole, and this could all be quite wrong as a result. I'll continue to investigate, but for now my advice is that you just don't use these mods at the same time. (Or don't use those settings)

There are a couple of changes I can do on this side to make this process easier, but realistically the majority of the fix probably needs to happen with their mod, since they're the ones manipulating inventories.

**Comment by CartoonishVillain** [comment]
Upon further inspection it appears some of my assumptions may have been wrong. I am going to try an experimental fix where I just ramp up the priority of my death events. If it works, great, if not. Well I'll keep looking. This issue will close when these updates are available. If the issue persists after, attempt to open this ticket back up (or comment on it). Otherwise make a new ticket. 

Thank you for bringing this to my attention!

**Comment by CartoonishVillain** [comment]
I do apologize, but due to my lack of familiarity with the mod at hand I can not effectively test this fix. Please attempt this with the new 1.2.2 forge builds and let me know how it goes, closing this ticket for now.

**Comment by Kzeroko** [comment]
> I do apologize, but due to my lack of familiarity with the mod at hand I can not effectively test this fix. Please attempt this with the new 1.2.2 forge builds and let me know how it goes, closing this ticket for now.

Hello, I just tested out the new build in my modpack and the bug is fixed. I did multiple random death tests without losing my inventory. If there are any further issues I will still reply to this ticket,  but right now things work just fine. Thank you so much!

**Comment by CartoonishVillain** [comment]
Fantastic to hear! Again, thank you for bringing it up!
