### ISSUE TITLE
Too easy to exploit this mod. Need a way to disable attacking monsters.

### ISSUE THREAD

**Issue by MaxwellGumley** [CartoonishVillain/Incapacitated#21]
First, this mod is awesome and really improves group play. It's probably the most important mod I have for playing with my kids.

I have a player on my server that just killed the warden while incapacitated. I wanted the younger players to be able to revive each other to keep the party together, but currently it's just too easy to kill the hard bosses like the warden, since they are invincible when down.

I know there are options to make the player die faster, but that's not what we need. There needs to be an option to disable attacking while the player is down.

**Comment by CartoonishVillain** [comment]
Hello! In newer versions of the mod, there is a config to apply what is effectively a large weakness debuff to the player.

This of course does not cover ranged attacks, but in order to do so I'd need to firefight against every possible attack method, including every modded item that does ranged damage which is a bit steep.

I may add an experimental toggle in the next update though, which when enabled will see if the attacker of a damage source is a downed player and negate damage all together. 

I do want to avoid making that default, as I'm sure it could cause some confusion and frustration with players who may not understand.

Will make an update related to this in the coming week. Thank you for sharing your feedback!

**Comment by CartoonishVillain** [comment]
A bit of delay on this patch, I apologize, life suddenly got quite busy. I'll try to get this out as soon as I can.

**Comment by CartoonishVillain** [comment]
This has been addressed in 1.8.2LTS for fabric 1.20.1, and 1.8.2 for the 1.21.1 versions. Thank you again for reporting!

This is addressed in the new "DANGERDisableIncapPlayerDamage" config option. This will not generate in your JSON config file automatically, unless you delete the file in its entirety, or remove it from the config directly. You can alternatively add the value manually to your config to enable it.

This is flagged with the "DANGER" tag, as while this method is much more effective, it handles removing attacks from players much more aggressively than just applying weakness, and may cause other strange and unexpected behaviors in doing so. I will not guarantee fixes for these, unless they are absolutely game breaking.

**Comment by MaxwellGumley** [comment]
You fixed it! Thank you! My kids are so happy this is fixed!  I'm able to disable incoming and outgoing player damage in the incapacitated config now.  This is critical when playing with little kids :)
